import type { Metadata } from "next";
import Image from 'next/image'
import localFont from "next/font/local";
import "./globals.css";
import Searchbar from "@/components/searchbar";
import logo from "@/assets/logo-mobile.png"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Aeralab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        <header>
          <nav className='flex items-center'>
            
              <Image src={logo} alt="" width={24} height={24} />
              Gaming Haven Z
          </nav>
          <Searchbar/>
        </header>
        {children}
      </body>
    </html>
  );
}
