import type { Metadata } from "next";
import Image from 'next/image'
import localFont from "next/font/local";
import "./globals.css";
import Searchbar from "@/components/searchbar";
import logo from "@/assets/logo-mobile.png"
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Aeralab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        <Header>
          <Searchbar/>
        </Header>
        <main className='lg:max-w-screen-md lg:mx-auto'>
          {children}
        </main>
      </body>
    </html>
  );
}
